import { useMemo, useState } from "react";
import { postJson } from "../api/client";

const tabs = [["overview", "经营总览", "◈"], ["brief", "营销 Brief", "▤"], ["acquisition", "逆向获客", "⌁"], ["evidence", "数据证据", "◌"], ["market", "市场洞察", "◎"], ["models", "增长模型", "△"], ["products", "商品与Listing", "□"], ["content", "内容与渠道", "✦"], ["campaign", "年度战役", "◷"], ["profit", "利润与预算", "¥"], ["data", "归因与复盘", "∿"], ["operations", "组织与风险", "＋"], ["execution", "运行日志", "⋮"], ["simulation", "经营模拟", "∑"]] as const;

export function BrandStrategyPage() {
  const [form, setForm] = useState({ brand_name: "云水禾", category: "东方雅致女装", audience: "25-40岁城市女性", objective: "建立差异化认知并提升内容带来的成交", source_urls_text: "", data_notes: "", use_model: true });
  const [activeTab, setActiveTab] = useState<(typeof tabs)[number][0]>("overview");
  const [data, setData] = useState<any>(null);
  const [busy, setBusy] = useState<"template" | "model" | "">("");
  const [error, setError] = useState("");
  const [simulation, setSimulation] = useState<any>(null);
  const [workflow, setWorkflow] = useState<any>(null);

  const workflowPayload = { ...form, source_urls: form.source_urls_text.split(/\n|,|，/).map((item) => item.trim()).filter(Boolean), use_model: true };

  const run = async (mode: "template" | "model") => {
    setBusy(mode); setError("");
    try {
      if (mode === "model") {
        const response = await postJson("/api/brand-strategy/workflow/run", { ...workflowPayload, workflow_id: `brand-${Date.now()}` });
        if (!response || !["ok", "partial"].includes(response.status)) throw new Error(response?.message || "全链路分析失败");
        const result = response.data || {};
        setWorkflow(result);
        const strategy = result.report?.strategy || result.outputs?.generate_strategy?.strategy || null;
        setData(strategy ? { ...strategy, _report: result.report } : null);
        setSimulation(result.report?.simulation || result.outputs?.simulate_campaign?.simulation || null);
        setActiveTab("overview");
        if (response.warnings?.length || result.report?.quality?.data_gaps?.length) {
          setError([...(response.warnings || []), ...(result.report?.quality?.data_gaps || []).map((item: string) => `数据缺口：${item}`)].join("；"));
        }
        return;
      }
      const response = await postJson("/api/brand-strategy/template", { ...workflowPayload, use_model: false });
      if (!response || !["ok", "partial"].includes(response.status)) throw new Error(response?.message || "分析生成失败");
      setData(response.data); setActiveTab("overview");
      if (response.warnings?.length) setError(response.warnings.join("；"));
    } catch (reason) { setError(reason instanceof Error ? reason.message : "分析生成失败"); }
    finally { setBusy(""); }
  };

  const runSimulation = async () => {
    setBusy("model"); setError("");
    try { const response = await postJson("/api/brand-strategy/simulate", {}); if (response.status !== "ok") throw new Error(response.message || "经营模拟失败"); setSimulation(response.data); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "经营模拟失败"); }
    finally { setBusy(""); }
  };

  const runWorkflow = () => { setError(""); setActiveTab("execution"); };

  const templatePreview = useMemo(() => ({ brand_name: form.brand_name, category: form.category, audience: form.audience, objective: form.objective, executive_summary: "先生成一份内置模板，系统会把品牌目标拆解为认知、兴趣、考虑、转化和复购推荐五个阶段。", funnel: { stages: [] }, aarrr: { stages: [] }, model_comparison: [], annual_nodes: [], budget_model: { default_allocation: [], guardrails: [] }, operating_foundation: { target_tree: { kpis: [] }, profit_budget: { allocation: [], guardrails: [] }, battle_plan: { dimensions: [], product_roles: [] }, promotion_phases: [], data_attribution: { dashboards: [], experiments: [] }, org_risk: { raci: [], risks: [] } }, flywheel: { steps: [] }, market_insights: [], trend_summary: [], recommendations: [] }), [form]);
  const current = data || templatePreview;
  return <div className="brand-strategy-page">
    <div className="brand-strategy-head"><div><p>BRAND GROWTH STRATEGY / V1</p><h1>品牌营销全案策划</h1><span>把市场判断、用户路径与营销动作放到同一张策略地图里</span></div><div className="brand-source-badge"><i />{data?.generated ? "真实文本模型已生成" : "内置模板可直接使用"}</div></div>
    <section className="brand-intake"><div className="brand-intake-copy"><span className="brand-kicker">经营问题 → 数据证据 → 策略动作</span><h2>生成一份可以被验证、被执行、被复盘的品牌经营报告</h2><p>模型生成分析会自动运行后端全链路；内部技术架构和业务架构隐藏在工作流日志中，前端只呈现经营结论、证据质量、指标口径和下一步动作。</p></div><div className="brand-form"><label>品牌名称<input value={form.brand_name} onChange={(e) => setForm({ ...form, brand_name: e.target.value })} /></label><label>所在品类<input value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} /></label><label>核心人群<input value={form.audience} onChange={(e) => setForm({ ...form, audience: e.target.value })} /></label><label className="wide">本阶段目标<input value={form.objective} onChange={(e) => setForm({ ...form, objective: e.target.value })} /></label><label className="wide data-input">真实数据入口（可粘贴链接、平台导出摘要或 JSON）<textarea value={form.data_notes} onChange={(e) => setForm({ ...form, data_notes: e.target.value })} placeholder={'例如：店铺链接、商品链接、近90天经营数据；也可粘贴 JSON：{"transactions":{"gmv":120000,"orders":300},"traffic":{"clicks":5000,"impressions":100000}}'} /></label><label className="wide">公开资料链接（每行一个）<input value={form.source_urls_text} onChange={(e) => setForm({ ...form, source_urls_text: e.target.value })} placeholder="官网、店铺、社媒、竞品或报告链接" /></label><div className="brand-actions"><button className="secondary" disabled={Boolean(busy)} onClick={() => run("template")} type="button">{busy === "template" ? "生成中…" : "使用内置模板"}</button><button className="primary" disabled={Boolean(busy)} onClick={() => run("model")} type="button">{busy === "model" ? "全链路生成中…" : "模型生成分析 ↗"}</button><button className="workflow" disabled={Boolean(busy)} onClick={runWorkflow} type="button">查看运行日志 · {workflow ? "已完成" : "未运行"}</button></div></div></section>
    {error ? <div className="brand-warning">模型提示：{error}</div> : null}
    <nav className="brand-tabs" aria-label="品牌经营策略报告模块">{tabs.map(([key, label, icon]) => <button className={activeTab === key ? "active" : ""} key={key} onClick={() => setActiveTab(key)} type="button"><i aria-hidden="true">{icon}</i><span>{String(tabs.findIndex((item) => item[0] === key) + 1).padStart(2, "0")}</span>{label}</button>)}</nav>
    <section className="brand-output"><div className="brand-output-top"><div><span className="brand-kicker">{current.category || "目标品类"} · {current.audience || "核心人群"}</span><h2>{activeTab === "overview" ? current.brand_name : tabs.find((item) => item[0] === activeTab)?.[1]}</h2></div><span className="brand-output-status">{data?.generated ? "MODEL GENERATED" : "TEMPLATE READY"}</span></div>{activeTab === "overview" ? <Overview data={current} onNavigate={setActiveTab} /> : activeTab === "brief" ? <BriefPanel report={current._report} /> : activeTab === "acquisition" ? <ReverseAcquisitionPanel report={current._report} /> : activeTab === "evidence" ? <EvidencePanel report={current._report} /> : activeTab === "market" ? <MarketPanel data={current} /> : activeTab === "models" ? <GrowthModels data={current} /> : activeTab === "products" ? <ListingPanel report={current._report} /> : activeTab === "content" ? <ContentPanel data={current} /> : activeTab === "campaign" ? <CampaignPanel data={current} /> : activeTab === "profit" ? <ProfitPanel data={current} simulation={simulation} /> : activeTab === "data" ? <DataAttribution data={current.operating_foundation?.data_attribution} /> : activeTab === "operations" ? <OrgRisk data={current.operating_foundation?.org_risk} /> : activeTab === "execution" ? <ExecutionFlow workflow={workflow} /> : <Simulation data={simulation} busy={busy} onRun={runSimulation} />}</section>
  </div>;
}

function Overview({ data, onNavigate }: { data: any; onNavigate: (tab: typeof tabs[number][0]) => void }) { const moduleMap: Record<string, typeof tabs[number][0]> = { overview: "overview", brief: "brief", acquisition: "acquisition", market: "market", audience: "models", listing: "products", campaign: "campaign", profit: "profit", operations: "operations", data: "data" }; return <><div className="brand-summary"><span>EXECUTIVE SUMMARY</span><p>{data.executive_summary}</p></div>{data._report?.sections?.length ? <div className="report-sections"><span>REPORT MODULES / 已生成模块</span><div>{data._report.sections.map((section: any, index: number) => <button key={section.id} onClick={() => onNavigate(moduleMap[section.id] || "overview")} type="button"><b>0{index + 1}</b>{section.title}<em>{section.status}</em></button>)}</div></div> : null}<div className="brand-overview-grid"><div><span>核心判断</span><strong>先找流失点，再分配预算</strong><small>用漏斗定位问题，用 AARRR 判断增长是否可持续。</small></div><div><span>策略资产</span><strong>Brief · VOC · 内容 · 指标</strong><small>先建立营销决策上下文，再进入内容和转化执行。</small></div><div><span>下一步</span><strong>补数据并验证机会</strong><small>用真实用户语言和成交数据校准用户模型与关键词。</small></div></div><div className="brand-recommendations"><span>建议行动</span>{(data.recommendations || []).map((item: string, index: number) => <div key={item}><b>0{index + 1}</b><p>{item}</p></div>)}</div></>; }
function BriefPanel({ report }: { report: any }) { const brief = report?.brief || {}; const qa = brief.qa || {}; return <div className="deep-panel"><div className="panel-lead"><span>MARKETING PLANNING BRIEF / {brief.status || "pending"}</span><h3>先形成营销决策上下文，再进入内容与投放执行</h3><p>这个模块回答业务目标、用户问题、市场机会、品牌价值、营销命题、渠道路径和 KPI 是否已经形成因果链。</p></div><div className="brief-score"><div><span>BRIEF QA</span><strong>{qa.score ?? "-"}</strong><small>/ 100 · {qa.status || "待评估"}</small></div><p>{brief.marketing_proposition || "等待品牌、用户和市场信息"}</p></div><div className="brief-grid">{[["业务目标", brief.objectives?.business_goal], ["营销目标", brief.objectives?.marketing_goal], ["传播目标", brief.objectives?.communication_goal], ["转化目标", brief.objectives?.conversion_goal], ["目标人群", (brief.audiences || []).map((item: any) => item.name).join("、")], ["价值主张", brief.positioning?.value_proposition]].map(([title, value]) => <article key={title}><span>{title}</span><strong>{value || "待补充"}</strong></article>)}</div><div className="action-plan"><span>30 / 60 / 90 DAYS</span>{Object.entries(brief.action_plan || {}).map(([period, actions]) => <article key={period}><b>{period.replace("_", " ")}</b><p>{(actions as string[]).join("；")}</p></article>)}</div></div>; }
function ReverseAcquisitionPanel({ report }: { report: any }) { const model = report?.reverse_acquisition || {}; return <div className="deep-panel"><div className="panel-lead"><span>USER REVERSE ENGINEERING ACQUISITION</span><h3>从商业结果倒推用户、Trigger、VOC、关键词和成交</h3><p>不是先写一张人口画像，而是找到用户为什么现在采取行动，以及品牌应该在哪个需求入口出现。</p></div><div className="reverse-flow">{(model.conversion_loop || []).map((step: string, index: number) => <span key={step}><b>0{index + 1}</b>{step}</span>)}</div><div className="reverse-grid"><article><span>用户模型</span><strong>{model.user?.who?.[0]?.role || "待确认"}</strong><p>Trigger：{(model.user?.trigger || []).slice(0, 3).join(" · ")}</p><p>JTBD：{model.user?.jtbd}</p></article><article><span>VOC 证据</span><strong>{model.voc?.length || 0} 条</strong><p>{model.voc?.map((item: any) => item.text).join("；") || "等待评论、客服、搜索词或评价数据"}</p></article></div><div className="keyword-table"><div className="keyword-head"><span>关键词</span><span>意图</span><span>机会分</span><span>内容/CTA</span></div>{(model.keywords || []).map((item: any) => <div key={item.keyword}><strong>{item.keyword}</strong><span>{item.intent}</span><b>{item.score}</b><small>{item.content_angle} → {item.cta}</small></div>)}</div></div>; }
function EvidencePanel({ report }: { report: any }) { const intelligence = report?.intelligence || {}; const gaps = intelligence.quality?.missing_fields || report?.quality?.data_gaps || report?.evidence?.missing_data || ["尚未接入真实平台指标"]; const sources = intelligence.dataset?.source_count ?? report?.evidence?.source_count ?? report?.evidence?.evidence_sources?.length ?? 0; return <div className="evidence-panel"><div className="evidence-hero"><div><span>DATA READINESS / {intelligence.data_mode || "pending"}</span><h3>{sources ? `${sources} 个资料入口已登记` : "等待真实数据输入"}</h3><p>报告会把结论拆成事实、推断、假设和行动；没有证据的地方不会生成确定性经营结论。</p></div><strong className={gaps.length ? "partial" : "ready"}>{intelligence.quality?.status || (gaps.length ? "LIMITED" : "READY")}</strong></div><div className="evidence-grid"><article><b>01</b><strong>已验证事实</strong><p>{intelligence.claims?.filter((item: any) => item.type === "fact").map((item: any) => item.statement).join("；") || "品牌基础信息已登记，等待商品、平台和订单数据验证。"}</p></article><article><b>02</b><strong>确定性特征</strong><p>{intelligence.features?.filter((item: any) => item.value !== null).map((item: any) => `${item.name}=${item.value}`).join(" · ") || "等待结构化经营数据后计算 CTR、CVR、AOV、ROAS 等特征。"}</p></article><article><b>03</b><strong>数据缺口</strong><p>{gaps.join("；")}</p></article><article><b>04</b><strong>下一轮验证</strong><p>{intelligence.quality?.recommendation || "优先补充近90天订单、广告消耗、商品 SKU、毛利、评价和复购数据。"}</p></article></div><div className="evidence-contract"><span>ANALYSIS CONTRACT</span><div><em>事实</em><em>特征</em><em>诊断</em><em>假设</em><em>实验</em></div></div></div>; }
function MarketPanel({ data }: { data: any }) { return <div className="deep-panel"><div className="panel-lead"><span>MARKET / SIGNAL / DECISION</span><h3>市场洞察不是趋势罗列，而是机会判断</h3><p>每条洞察都要回答：发生了什么、依据是什么、对品牌意味着什么、下一步验证什么。</p></div><InsightList items={data.market_insights} /><TrendList items={data.trend_summary} /></div>; }
function GrowthModels({ data }: { data: any }) { const intelligence = data._report?.intelligence || {}; return <div className="deep-panel"><div className="panel-lead"><span>MODEL STACK / {intelligence.quality?.status || "PREVIEW"}</span><h3>AIPL 管人群资产，AARRR 管长期增长，漏斗管当前流失</h3><p>模型不是结论，只有绑定事件、指标、基线和动作后，才可以用于预算与复盘。当前诊断：{intelligence.diagnosis?.problem_nodes?.[0]?.question || "等待真实漏斗数据"}。</p></div><ModelCompare items={data.model_comparison} /><div className="model-depth-grid"><div><h4>漏斗诊断</h4><Funnel data={intelligence.models?.funnel || data.funnel} /></div><div><h4>AARRR 留存</h4><AARRR data={data.aarrr} /></div></div><div className="opportunity-list"><span>OPPORTUNITIES / 待验证机会</span>{(intelligence.opportunities || []).map((item: any) => <article key={item.opportunity_id}><b>{item.priority}</b><strong>{item.statement}</strong><small>置信度 {item.confidence} · 状态 {item.status}</small></article>)}</div></div>; }
function ListingPanel({ report }: { report: any }) { const listing = report?.listing || {}; return <div className="deep-panel"><div className="panel-lead"><span>LISTING / PRODUCT FACTS → CONVERSION</span><h3>商品呈现是策略落地的第一承接面</h3><p>后续接入真实商品数据后，这里将扩展到 SKU、价格带、评价主题、主图/详情页证据和平台关键词。</p></div><div className="listing-card"><div><span>Listing ID</span><strong>{listing.listing_id || "等待生成"}</strong></div><div><span>证据状态</span><strong>{listing.evidence_status || "template"}</strong></div><div><span>品牌主张</span><p>{listing.brand_proposition || "待补充真实商品与品牌资料"}</p></div><div><span>内容支柱</span><p>{(listing.content_pillars || []).join(" · ") || "卖点、场景、证据、服务"}</p></div></div></div>; }
function ContentPanel({ data }: { data: any }) { return <div className="deep-panel"><div className="panel-lead"><span>CONTENT / CHANNEL / LANDING</span><h3>内容必须有主题、证据、承接页和归因事件</h3><p>先按认知、兴趣、考虑、购买、忠诚拆内容，再用真实 CTR、完播、搜索提升、加购和支付数据校准。</p></div><div className="content-matrix">{["认知：场景与差异记忆", "兴趣：痛点与产品证据", "考虑：对比、口碑与服务", "转化：权益、直播与商品页", "忠诚：使用教育、复购与推荐"].map((item, index) => <article key={item}><b>0{index + 1}</b><strong>{item}</strong><span>待绑定：内容主题 · 素材 · 渠道 · 承接 · 指标</span></article>)}</div><TrendList items={data.trend_summary} /></div>; }
function CampaignPanel({ data }: { data: any }) { return <div className="deep-panel"><div className="panel-lead"><span>ANNUAL BATTLE MAP</span><h3>节点按蓄水、爆发、返场、留存管理</h3><p>每个节点同时承接生意结果、增长效率、用户资产和品牌资产。</p></div><AnnualNodes items={data.annual_nodes} /><Phases items={data.operating_foundation?.promotion_phases} /></div>; }
function ProfitPanel({ data, simulation }: { data: any; simulation: any }) { return <div className="deep-panel"><div className="panel-lead"><span>PROFIT / BUDGET / STOCK</span><h3>先看贡献毛利，再决定是否放量</h3><p>预算、库存、退款、履约和复购必须放在同一个经营约束里。</p></div><BudgetModel data={data.budget_model} /><ProfitBudget data={data.operating_foundation?.profit_budget} />{simulation ? <div className="profit-snapshot"><span>模拟结果</span><strong>贡献毛利 ROI {((simulation.summary?.contribution_roi || 0) * 100).toFixed(1)}%</strong><small>LTV/CAC {simulation.summary?.ltv_cac ?? "-"} · Blended CAC {simulation.summary?.blended_cac ?? "-"}</small></div> : null}</div>; }
function Funnel({ data }: { data: any }) { return <><div className="brand-model-note">{data?.bottleneck || "漏斗模型：从被看见到被推荐，逐层检查用户为什么继续或离开。"}</div><div className="funnel-stack">{(data?.stages || []).map((stage: any, index: number) => <article className={`funnel-stage stage-${index}`} key={stage.key}><b>0{index + 1}</b><div><strong>{stage.name}</strong><span>{stage.question}</span></div><em>{stage.metric}</em><p>{stage.action}</p></article>)}</div></>; }
function AARRR({ data }: { data: any }) { return <><div className="brand-model-note">北极星指标：{data?.north_star || "让用户完成首次关键体验，并持续复访。"}</div><div className="aarrr-grid">{(data?.stages || []).map((stage: any, index: number) => <article key={stage.key}><span>0{index + 1}</span><strong>{stage.name}</strong><p>{stage.focus}</p><div>{(stage.metrics || []).map((metric: string) => <em key={metric}>{metric}</em>)}</div></article>)}</div></>; }
function ModelCompare({ items }: { items: any[] }) { return <div className="model-compare">{(items || []).map((item) => <article key={item.model}><div className="model-compare-title"><strong>{item.model}</strong><span>{item.type}</span></div><h3>{item.stages}</h3><p>{item.best_for}</p><small><b>ROI 问题：</b>{item.roi_question}</small></article>)}</div>; }
function Targets({ data }: { data: any }) { return <><div className="brand-model-note">{data?.formula}<br />北极星：{data?.north_star}<br />增量口径：{data?.incremental_rule}</div><div className="foundation-grid">{(data?.kpis || []).map((item: any) => <article key={item.layer}><span>{item.layer}</span><strong>{item.metrics.join(" · ")}</strong><small>{item.decision}</small></article>)}</div></>; }
function AnnualNodes({ items }: { items: any[] }) { return <div className="annual-nodes">{(items || []).map((item) => <article key={item.node}><div><strong>{item.node}</strong><span>{item.goal}</span></div><p><b>模型：</b>{item.models}</p><p><b>人群：</b>{item.audience}</p><small><b>KPI：</b>{item.kpi}</small></article>)}</div>; }
function BudgetModel({ data }: { data: any }) { return <><div className="brand-model-note">{data?.formula}</div><div className="budget-layout"><div className="budget-bars">{(data?.default_allocation || []).map((item: any) => <div key={item.name}><div><span>{item.name}</span><b>{item.percent}%</b></div><i><em style={{ width: `${item.percent}%` }} /></i></div>)}</div><div className="budget-guardrails"><span>预算护栏</span>{(data?.guardrails || []).map((item: string) => <p key={item}>↳ {item}</p>)}</div></div></>; }
function ProfitBudget({ data }: { data: any }) { return <><div className="brand-model-note">{data?.pnl_formula}</div><div className="foundation-table">{(data?.allocation || []).map((item: any) => <div key={item.name}><strong>{item.name}</strong><b>{item.percent}</b><span>{item.items}</span></div>)}</div><div className="guardrail-row">{(data?.guardrails || []).map((item: string) => <em key={item}>{item}</em>)}</div></>; }
function BattlePlan({ data }: { data: any }) { return <><div className="foundation-table">{(data?.dimensions || []).map((item: any) => <div key={item.dimension}><strong>{item.dimension}</strong><span>{item.deliverable}</span></div>)}</div><div className="role-pills">{(data?.product_roles || []).map((item: string) => <em key={item}>{item}</em>)}</div></>; }
function Phases({ items }: { items: any[] }) { return <div className="phase-list">{(items || []).map((item, index) => <article key={item.phase}><b>0{index + 1}</b><div><strong>{item.phase}</strong><span>{item.timing}</span><p>{item.actions}</p><small>指标：{item.metrics}</small></div></article>)}</div>; }
function DataAttribution({ data }: { data: any }) { return <><div className="foundation-grid">{(data?.dashboards || []).map((item: string) => <article key={item}><span>看板</span><strong>{item}</strong></article>)}</div><div className="role-pills">{(data?.experiments || []).map((item: string) => <em key={item}>A/B · {item}</em>)}</div><div className="brand-model-note">归因护栏：{data?.attribution_guardrail}</div></>; }
function OrgRisk({ data }: { data: any }) { return <><div className="foundation-table">{(data?.raci || []).map((item: any) => <div key={item.role}><strong>{item.role}</strong><span>{item.owns}</span></div>)}</div><div className="risk-list">{(data?.risks || []).map((item: string, index: number) => <span key={item}><b>R{index + 1}</b>{item}</span>)}</div></>; }
function Simulation({ data, busy, onRun }: { data: any; busy: string; onRun: () => void }) { if (!data) return <div className="simulation-empty"><p>使用两份 Excel 模板中的默认假设，计算渠道 ROAS、贡献毛利 ROI、CAC、LTV/CAC、AIPL/FAST 和库存风险。</p><button className="primary" disabled={Boolean(busy)} onClick={onRun} type="button">{busy ? "计算中…" : "运行经营模拟 ↗"}</button></div>; return <><div className="simulation-note">{data.assumption_note}</div><div className="simulation-kpis">{[["预算", data.summary.budget], ["净销售额", data.summary.net_sales], ["贡献毛利", data.summary.contribution_profit], ["贡献毛利 ROI", `${(data.summary.contribution_roi * 100).toFixed(1)}%`], ["Blended CAC", data.summary.blended_cac], ["LTV/CAC", data.summary.ltv_cac]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{typeof value === "number" ? value.toLocaleString("zh-CN", { maximumFractionDigits: 2 }) : value}</strong></div>)}</div><div className="simulation-columns"><div><h3>渠道预测</h3><div className="simulation-table">{data.channels.map((item: any) => <div key={item.name}><strong>{item.name}</strong><span>ROAS {item.roas}</span><span>CAC {item.paid_cac ?? "-"}</span><b>贡献 ROI {(item.contribution_roi * 100).toFixed(1)}%</b></div>)}</div></div><div><h3>库存风险</h3><div className="simulation-table">{data.inventory.map((item: any) => <div key={item.role}><strong>{item.role}</strong><span>预测 {item.forecast_sales}</span><span>建议备货 {item.recommended_stock}</span><b className={item.stock_gap > 0 ? "risk" : "safe"}>{item.risk}</b></div>)}</div></div></div></>; }
function ArchitectureFlow({ title, items, tone }: { title: string; items: any[]; tone: "business" | "technical" }) { return <div className={`architecture-flow ${tone}`}><div className="architecture-caption"><span>BACKEND CONTRACT</span><p>{tone === "business" ? "业务边界：从商品事实到 Listing，再到营销增长与性能反馈。" : "技术边界：API 入口、DAG 编排、Agent/Skill、证据存储与 Trace。"}</p></div><div className="architecture-nodes">{(items || []).map((item, index) => <div className="architecture-node" key={item.id}><b>0{index + 1}</b><div><strong>{item.label}</strong><span>{item.description || item.component}</span></div>{index < (items || []).length - 1 ? <i>↓</i> : null}</div>)}</div></div>; }
function ExecutionFlow({ workflow }: { workflow: any }) { if (!workflow) return <div className="execution-empty"><p>点击上方“运行品牌全链路”，后端将按 DAG 节点依次执行并回传 Trace。</p></div>; const outputs = workflow.outputs || {}; return <div className="execution-flow"><div className="execution-summary"><span>WORKFLOW: {workflow.status}</span><strong>{Object.keys(outputs).length} 个节点已执行</strong><small>顺序：{(workflow.order || []).join(" → ")}</small></div><div className="execution-nodes">{(workflow.order || []).map((node: string, index: number) => <article key={node}><b>0{index + 1}</b><div><strong>{node}</strong><span>{outputs[node]?.status || "completed"}</span><small>{outputs[node]?.message || outputs[node]?.note || outputs[node]?.next_action?.join("；") || "节点输出已写入工作流结果"}</small></div></article>)}</div>{workflow.trace_summary ? <div className="brand-model-note">Trace：{JSON.stringify(workflow.trace_summary)}</div> : null}</div>; }
function Flywheel({ data }: { data: any }) { return <><div className="brand-model-note">{data?.north_star}<br />首购激活窗口：{data?.activation_window}</div><div className="flywheel"><div className="flywheel-ring">用户<br />飞轮</div>{(data?.steps || []).map((step: string, index: number) => <div className={`flywheel-step flywheel-step-${index}`} key={step}><b>0{index + 1}</b><span>{step}</span></div>)}</div></>; }
function InsightList({ items }: { items: any[] }) { return <div className="brand-insight-list">{(items || []).map((item) => <article key={item.title}><span>INSIGHT</span><h3>{item.title}</h3><p>{item.evidence}</p><strong>策略含义</strong><small>{item.implication}</small></article>)}</div>; }
function TrendList({ items }: { items: any[] }) { return <div className="brand-trend-list">{(items || []).map((item, index) => <article key={item.trend}><b>0{index + 1}</b><div><h3>{item.trend}</h3><span>{item.signal}</span><p><strong>建议动作：</strong>{item.move}</p></div></article>)}</div>; }
